### ISSUE TITLE
Bug: Getting error when compile source code `cmake . && make`

### ISSUE THREAD

**Issue by chungquantin** [unum-cloud/ukv#248]
### Describe the bug

Follow the contribution guide `cmake . && make` and get these errors.

Are there any hardware requirements or compatible version of `clang` or `make` to set up the project? I try to run `make` and the terminal throws these errors. I think this error is from a syntax level.

<img width="1132" alt="Screen Shot 2023-02-02 at 13 40 39" src="https://user-images.githubusercontent.com/56880684/216419670-94edbf5d-e42b-4f2c-925e-8e6107758208.png">

On the other hand, I tried building UKV from source following this docs (https://unum.cloud/ukv/install.html) and get another error with linker.

<img width="1119" alt="Screen Shot 2023-02-02 at 13 45 29" src="https://user-images.githubusercontent.com/56880684/216420654-848edf8c-fc01-45ff-8f66-71df41393610.png">

### Steps to reproduce

- Make version: `GNU Make 3.81`
- Clang version: `Homebrew clang version 15.0.7`
- OS: MacOS M1
- Target: arm64-apple-darwin20.6.0

### Expected behavior

Install and

### UKV version

0.4.2383

### Operating System

MacOS Big Sur 11.5.2

### Hardware architecture

Arm

### Are you using an embedded version?

- [ ] I use the embedded version

### Which interface are you using?

Native C interface

### Which engine are you using?

Other

### Contact Details

cqtin0903@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
I believe those compilation issues have been resolved in the last couple of days. Have you tried clearing caches for CMake to pull newer ucset?

**Comment by chungquantin** [comment]
@ashvardanian Did try to remove all caches and even reinstall `cmake` and `clang`. However, still get same error.

**Comment by ashvardanian** [comment]
@chungquantin Sorry for making you wait. I am preparing 2 more libraries to be open-sourced in the following few days.

First of all, I don't recommend running CMake in the same directory. I generally split folders for debug and release builds, like it is [mentioned](https://unum.cloud/ukv/install.html#building-from-source) in the documentation. Here is a copy:

```sh
cmake \
    -DUKV_BUILD_ENGINE_UMEM=1 \
    -DUKV_BUILD_ENGINE_LEVELDB=1 \
    -DUKV_BUILD_ENGINE_ROCKSDB=1 \
    -DUKV_BUILD_TESTS=1 \
    -DUKV_BUILD_BENCHMARKS=1 \
    -DUKV_BUILD_API_FLIGHT_CLIENT=0 \
    -DUKV_BUILD_API_FLIGHT_SERVER=0 \
    -B ./build_release && \
make -j16 -C ./build_release
```

Moreover, if you are using VSCode, there are some pre-configured tasks/launchers you can use to cleanup the environment and start all over.

---

Those suggestions aside, I have just tried building on Ubuntu with GCC and Clang. To override the compiler - pass an environment variable like this:

```sh
CC=clang CXX=clang++ cmake     -DUKV_BUILD_ENGINE_UMEM=1     -DUKV_BUILD_ENGINE_LEVELDB=1     -DUKV_BUILD_ENGINE_ROCKSDB=1     -DUKV_BUILD_TESTS=1     -DUKV_BUILD_BENCHMARKS=1     -DUKV_BUILD_API_FLIGHT_CLIENT=0     -DUKV_BUILD_API_FLIGHT_SERVER=0     -B ./build_release && make -j16 -C ./build_release
```

Both builds pass, but Clang is a bit stricter with compiler flags. I will loosen those constraints now, but none of them cause the bugs you reported. Those were solved a long time ago. You must clean the environment, especially the `_deps` folder, and run the build.
